### ISSUE TITLE
Suggestion to deal with vision_msgs API break

### ISSUE THREAD

**Issue by Yadunund** [o3de/ROSConDemo#125]
Just sharing a suggestion to deal with the API break in `vision_msgs` between `galactic` and `humble` version that would allow this codebase to compile on both platfoms without the need to comment/uncomment lines of code like in [AppleDetectionGroundTruth](https://github.com/aws-lumberyard/ROSConDemo/blob/4dac3151db0da4b33521b6aad832bf383502d55e/Project/Gem/Source/ApplePicker/AppleDetectionGroundTruth.cpp#L87-L92).

1. Update `CMakeLists.txt` [here](https://github.com/aws-lumberyard/ROSConDemo/blob/4dac3151db0da4b33521b6aad832bf383502d55e/Project/Gem/CMakeLists.txt#L24) to add a compile definition flag depending on the `ROS_DISTRO` environment variable.

```
if("$ENV{ROS_DISTRO}" STREQUAL "galactic")
  add_definitions(-DROS2_GALACTIC)
endif()
```
2. Update the implementation of `AppleDetectionGroundTruth::Construct2DDetection` and `AppleDetectionGroundTruth::ConstructROS2Detection3DMessage` to compile different code paths depending on the definition added in 1.
For example: 
```
    vision_msgs::msg::Detection2D AppleDetectionGroundTruth::Construct2DDetection(const PickAppleTask& apple)
    {
        // code

        #ifdef ROS2_GALACTIC
            detection.bbox.center.position.x = apple.m_middle.GetX();
            detection.bbox.center.position.y = apple.m_middle.GetY();
        #else
            detection.bbox.size_x = apple.m_appleBoundingBox.GetExtents().GetX();
            detection.bbox.size_y = apple.m_appleBoundingBox.GetExtents().GetY();
        #endif
        return detection;
    }

```
Other minor suggestions:
Store detections as `unique_ptrs` of msgs -> Call `std::make_unique()` to instantiate the msgs within the respective "Construction" functions -> Update `Publish()` to use move semantics: publisher->publish(std::move(m_detection_msg))`
Using move semantics to transfer ownership of msg to the rclcpp layer can potentially allow for more efficient message transport if the publisher and subscribers are running in the same process (eg. with ROS 2 composition). This can short-circuit the serialization/deserialization at the rmw layer for better performance.

If these changes sound ok, I'm happy to open a PR.

**Comment by adamdbrw** [comment]
This seems simple enough to implement. @Yadunund are you still planning to contribute this?

**Comment by j-rivero** [comment]
We were able to build the docker image on Galactic so I think that the code is fully compatible. I'm closing the issue, please reopen if more things needs to happen in the scope of this issue.
