### ISSUE TITLE
RVIZ setup wrong map topics out-of-the-box if shiny is used

### ISSUE THREAD

**Issue by j-rivero** [o3de/ROSConDemo#160]
## Summary

Using `shiny` instead of `rusty` to spawn the first robot and launching the navigation leaves the user without a view of the navigation map in RVIZ. The values can be changed manually, not difficult. 

![rviz-on-shiny-not-work-out-of-the-box](https://user-images.githubusercontent.com/2098802/195899744-7830915e-0edc-4b0a-82ad-3dc2117b7520.gif)

I've been looking into the code ([probably here](https://github.com/RobotecAI/o3de_kraken_nav/blob/main/launch/config/config_multi.rviz)) but I'm not sure about the approach done there to support multirobot.

## Environment conditions 

**Machine specs:** **Machine specs:** AMD Ryzen 9 5900X 12-Core Processor, 32GB RAM, NVIDIA GeForce RTX 3060
**Code origin:**
```
o3de : roscon_2022
d644db1335e0d8c8afc2122b6c0054faab408688
o3de-ros2-gem : development
a482df77071841661ed5dfae9e1f258e979c3ecc
ROSConDemo : jrivero/dockerfile
99b3a51022a4fd37b0bd7a29c1e0ae306fa311ee
o3de_kraken_nav : main
e947a61755901f35999f5353411f580c384bd456
```

## Reproduce the problem

1. Start the Editor, game mode
2. Spawn shiny `ros2 service call /spawn_entity gazebo_msgs/srv/SpawnEntity '{name: 'apple_kraken_shiny', xml: 'line1'}'`
3. Launch navigation with shiny namespaces `ros2 launch o3de_kraken_nav navigation_multi.launch.py namespace:=apple_kraken_shiny_1 rviz:=True`

**Comment by adamdbrw** [comment]
I believe this issue could be closed. Our way of using a single RViz2 is not flexible, but it is a shortcoming of the solution rather than a bug. We might consider using multiple RViz2 windows or switching to orchestration.
