### ISSUE TITLE
Update Apple Kraken to match Joint Motor Controller Components

### ISSUE THREAD

**Issue by alek-kam-robotec-ai** [o3de/ROSConDemo#239]
The current state of the Apple Kraken prefabs is not compatible with the newly redesigned Motorized Joint and requires appropriate changes.

Required changes include:

- [ ] Use of PidMotorController in place of MotorizedJoint
- [ ] Configuring of the Pid controller values and Joint Limits
- [ ] Restructure of the Kraken Manipulator

**Comment by adamdbrw** [comment]
Better solution is to resolve https://github.com/o3de/ROSConDemo/issues/241
