### ISSUE TITLE
Update Demo to recent changes in o3de-extras

### ISSUE THREAD

**Issue by michalpelka** [o3de/ROSConDemo#241]
The change https://github.com/o3de/o3de-extras/commit/49c93314981303ee562cc9bd8987c312bfdd6bdf brought some changes in API causing some compilation errors:
```
/home/someuser/ROSConDemo/Project/Gem/Source/Manipulator/KrakenManipulatorController.cpp:10:10: fatal error: 'ROS2/Manipulator/MotorizedJointBus.h' file not found
#include <ROS2/Manipulator/MotorizedJointBus.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
Please adjust and test demo against new development of o3de-extras, or communicate which branch of o3de-extras should be used.

**Comment by adamdbrw** [comment]
Should wait for finalization of https://github.com/o3de/o3de-extras/pull/366 at least
